name: scheme_repl
description: Very basic Scheme REPL written in Dart
version: 0.0.1
repository: https://github.com/olexale/scheme_repl

environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_process: ^2.0.3
